/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sky.skyseries.apm.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Floor service. Represents a row in the &quot;apm_floor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sky.skyseries.apm.model.impl.FloorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sky.skyseries.apm.model.impl.FloorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Floor
 * @see com.sky.skyseries.apm.model.impl.FloorImpl
 * @see com.sky.skyseries.apm.model.impl.FloorModelImpl
 * @generated
 */
@ProviderType
public interface FloorModel extends BaseModel<Floor>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a floor model instance should use the {@link Floor} interface instead.
	 */

	/**
	 * Returns the primary key of this floor.
	 *
	 * @return the primary key of this floor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this floor.
	 *
	 * @param primaryKey the primary key of this floor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this floor.
	 *
	 * @return the uuid of this floor
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this floor.
	 *
	 * @param uuid the uuid of this floor
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the floor ID of this floor.
	 *
	 * @return the floor ID of this floor
	 */
	public long getFloorId();

	/**
	 * Sets the floor ID of this floor.
	 *
	 * @param floorId the floor ID of this floor
	 */
	public void setFloorId(long floorId);

	/**
	 * Returns the group ID of this floor.
	 *
	 * @return the group ID of this floor
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this floor.
	 *
	 * @param groupId the group ID of this floor
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this floor.
	 *
	 * @return the company ID of this floor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this floor.
	 *
	 * @param companyId the company ID of this floor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this floor.
	 *
	 * @return the user ID of this floor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this floor.
	 *
	 * @param userId the user ID of this floor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this floor.
	 *
	 * @return the user uuid of this floor
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this floor.
	 *
	 * @param userUuid the user uuid of this floor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this floor.
	 *
	 * @return the user name of this floor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this floor.
	 *
	 * @param userName the user name of this floor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this floor.
	 *
	 * @return the create date of this floor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this floor.
	 *
	 * @param createDate the create date of this floor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this floor.
	 *
	 * @return the modified date of this floor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this floor.
	 *
	 * @param modifiedDate the modified date of this floor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this floor.
	 *
	 * @return the name of this floor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this floor.
	 *
	 * @param name the name of this floor
	 */
	public void setName(String name);

	/**
	 * Returns the building ID of this floor.
	 *
	 * @return the building ID of this floor
	 */
	public long getBuildingId();

	/**
	 * Sets the building ID of this floor.
	 *
	 * @param buildingId the building ID of this floor
	 */
	public void setBuildingId(long buildingId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Floor floor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Floor> toCacheModel();

	@Override
	public Floor toEscapedModel();

	@Override
	public Floor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}