/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sky.skyseries.apm.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Room service. Represents a row in the &quot;apm_room&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sky.skyseries.apm.model.impl.RoomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sky.skyseries.apm.model.impl.RoomImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Room
 * @see com.sky.skyseries.apm.model.impl.RoomImpl
 * @see com.sky.skyseries.apm.model.impl.RoomModelImpl
 * @generated
 */
@ProviderType
public interface RoomModel extends BaseModel<Room>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a room model instance should use the {@link Room} interface instead.
	 */

	/**
	 * Returns the primary key of this room.
	 *
	 * @return the primary key of this room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this room.
	 *
	 * @param primaryKey the primary key of this room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this room.
	 *
	 * @return the uuid of this room
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this room.
	 *
	 * @param uuid the uuid of this room
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the room ID of this room.
	 *
	 * @return the room ID of this room
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this room.
	 *
	 * @param roomId the room ID of this room
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the group ID of this room.
	 *
	 * @return the group ID of this room
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this room.
	 *
	 * @param groupId the group ID of this room
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this room.
	 *
	 * @return the company ID of this room
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this room.
	 *
	 * @param companyId the company ID of this room
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this room.
	 *
	 * @return the user ID of this room
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this room.
	 *
	 * @param userId the user ID of this room
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this room.
	 *
	 * @return the user uuid of this room
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this room.
	 *
	 * @param userUuid the user uuid of this room
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this room.
	 *
	 * @return the user name of this room
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this room.
	 *
	 * @param userName the user name of this room
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this room.
	 *
	 * @return the create date of this room
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this room.
	 *
	 * @param createDate the create date of this room
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this room.
	 *
	 * @return the modified date of this room
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this room.
	 *
	 * @param modifiedDate the modified date of this room
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this room.
	 *
	 * @return the name of this room
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this room.
	 *
	 * @param name the name of this room
	 */
	public void setName(String name);

	/**
	 * Returns the floor ID of this room.
	 *
	 * @return the floor ID of this room
	 */
	public long getFloorId();

	/**
	 * Sets the floor ID of this room.
	 *
	 * @param floorId the floor ID of this room
	 */
	public void setFloorId(long floorId);

	/**
	 * Returns the room status ID of this room.
	 *
	 * @return the room status ID of this room
	 */
	public long getRoomStatusId();

	/**
	 * Sets the room status ID of this room.
	 *
	 * @param roomStatusId the room status ID of this room
	 */
	public void setRoomStatusId(long roomStatusId);

	/**
	 * Returns the room type ID of this room.
	 *
	 * @return the room type ID of this room
	 */
	public long getRoomTypeId();

	/**
	 * Sets the room type ID of this room.
	 *
	 * @param roomTypeId the room type ID of this room
	 */
	public void setRoomTypeId(long roomTypeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Room room);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Room> toCacheModel();

	@Override
	public Room toEscapedModel();

	@Override
	public Room toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}