/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sky.skyseries.apm.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.sky.skyseries.apm.model.Building;
import com.sky.skyseries.apm.service.BuildingService;
import com.sky.skyseries.apm.service.persistence.BuildingPersistence;
import com.sky.skyseries.apm.service.persistence.FloorPersistence;
import com.sky.skyseries.apm.service.persistence.LegalEntityPersistence;
import com.sky.skyseries.apm.service.persistence.RoomPersistence;
import com.sky.skyseries.apm.service.persistence.RoomStatusPersistence;
import com.sky.skyseries.apm.service.persistence.RoomTypePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the building remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.sky.skyseries.apm.service.impl.BuildingServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.sky.skyseries.apm.service.impl.BuildingServiceImpl
 * @see com.sky.skyseries.apm.service.BuildingServiceUtil
 * @generated
 */
public abstract class BuildingServiceBaseImpl extends BaseServiceImpl
	implements BuildingService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.sky.skyseries.apm.service.BuildingServiceUtil} to access the building remote service.
	 */

	/**
	 * Returns the building local service.
	 *
	 * @return the building local service
	 */
	public com.sky.skyseries.apm.service.BuildingLocalService getBuildingLocalService() {
		return buildingLocalService;
	}

	/**
	 * Sets the building local service.
	 *
	 * @param buildingLocalService the building local service
	 */
	public void setBuildingLocalService(
		com.sky.skyseries.apm.service.BuildingLocalService buildingLocalService) {
		this.buildingLocalService = buildingLocalService;
	}

	/**
	 * Returns the building remote service.
	 *
	 * @return the building remote service
	 */
	public BuildingService getBuildingService() {
		return buildingService;
	}

	/**
	 * Sets the building remote service.
	 *
	 * @param buildingService the building remote service
	 */
	public void setBuildingService(BuildingService buildingService) {
		this.buildingService = buildingService;
	}

	/**
	 * Returns the building persistence.
	 *
	 * @return the building persistence
	 */
	public BuildingPersistence getBuildingPersistence() {
		return buildingPersistence;
	}

	/**
	 * Sets the building persistence.
	 *
	 * @param buildingPersistence the building persistence
	 */
	public void setBuildingPersistence(BuildingPersistence buildingPersistence) {
		this.buildingPersistence = buildingPersistence;
	}

	/**
	 * Returns the floor local service.
	 *
	 * @return the floor local service
	 */
	public com.sky.skyseries.apm.service.FloorLocalService getFloorLocalService() {
		return floorLocalService;
	}

	/**
	 * Sets the floor local service.
	 *
	 * @param floorLocalService the floor local service
	 */
	public void setFloorLocalService(
		com.sky.skyseries.apm.service.FloorLocalService floorLocalService) {
		this.floorLocalService = floorLocalService;
	}

	/**
	 * Returns the floor remote service.
	 *
	 * @return the floor remote service
	 */
	public com.sky.skyseries.apm.service.FloorService getFloorService() {
		return floorService;
	}

	/**
	 * Sets the floor remote service.
	 *
	 * @param floorService the floor remote service
	 */
	public void setFloorService(
		com.sky.skyseries.apm.service.FloorService floorService) {
		this.floorService = floorService;
	}

	/**
	 * Returns the floor persistence.
	 *
	 * @return the floor persistence
	 */
	public FloorPersistence getFloorPersistence() {
		return floorPersistence;
	}

	/**
	 * Sets the floor persistence.
	 *
	 * @param floorPersistence the floor persistence
	 */
	public void setFloorPersistence(FloorPersistence floorPersistence) {
		this.floorPersistence = floorPersistence;
	}

	/**
	 * Returns the legal entity local service.
	 *
	 * @return the legal entity local service
	 */
	public com.sky.skyseries.apm.service.LegalEntityLocalService getLegalEntityLocalService() {
		return legalEntityLocalService;
	}

	/**
	 * Sets the legal entity local service.
	 *
	 * @param legalEntityLocalService the legal entity local service
	 */
	public void setLegalEntityLocalService(
		com.sky.skyseries.apm.service.LegalEntityLocalService legalEntityLocalService) {
		this.legalEntityLocalService = legalEntityLocalService;
	}

	/**
	 * Returns the legal entity remote service.
	 *
	 * @return the legal entity remote service
	 */
	public com.sky.skyseries.apm.service.LegalEntityService getLegalEntityService() {
		return legalEntityService;
	}

	/**
	 * Sets the legal entity remote service.
	 *
	 * @param legalEntityService the legal entity remote service
	 */
	public void setLegalEntityService(
		com.sky.skyseries.apm.service.LegalEntityService legalEntityService) {
		this.legalEntityService = legalEntityService;
	}

	/**
	 * Returns the legal entity persistence.
	 *
	 * @return the legal entity persistence
	 */
	public LegalEntityPersistence getLegalEntityPersistence() {
		return legalEntityPersistence;
	}

	/**
	 * Sets the legal entity persistence.
	 *
	 * @param legalEntityPersistence the legal entity persistence
	 */
	public void setLegalEntityPersistence(
		LegalEntityPersistence legalEntityPersistence) {
		this.legalEntityPersistence = legalEntityPersistence;
	}

	/**
	 * Returns the room local service.
	 *
	 * @return the room local service
	 */
	public com.sky.skyseries.apm.service.RoomLocalService getRoomLocalService() {
		return roomLocalService;
	}

	/**
	 * Sets the room local service.
	 *
	 * @param roomLocalService the room local service
	 */
	public void setRoomLocalService(
		com.sky.skyseries.apm.service.RoomLocalService roomLocalService) {
		this.roomLocalService = roomLocalService;
	}

	/**
	 * Returns the room remote service.
	 *
	 * @return the room remote service
	 */
	public com.sky.skyseries.apm.service.RoomService getRoomService() {
		return roomService;
	}

	/**
	 * Sets the room remote service.
	 *
	 * @param roomService the room remote service
	 */
	public void setRoomService(
		com.sky.skyseries.apm.service.RoomService roomService) {
		this.roomService = roomService;
	}

	/**
	 * Returns the room persistence.
	 *
	 * @return the room persistence
	 */
	public RoomPersistence getRoomPersistence() {
		return roomPersistence;
	}

	/**
	 * Sets the room persistence.
	 *
	 * @param roomPersistence the room persistence
	 */
	public void setRoomPersistence(RoomPersistence roomPersistence) {
		this.roomPersistence = roomPersistence;
	}

	/**
	 * Returns the room rate local service.
	 *
	 * @return the room rate local service
	 */
	public com.sky.skyseries.apm.service.RoomRateLocalService getRoomRateLocalService() {
		return roomRateLocalService;
	}

	/**
	 * Sets the room rate local service.
	 *
	 * @param roomRateLocalService the room rate local service
	 */
	public void setRoomRateLocalService(
		com.sky.skyseries.apm.service.RoomRateLocalService roomRateLocalService) {
		this.roomRateLocalService = roomRateLocalService;
	}

	/**
	 * Returns the room rate remote service.
	 *
	 * @return the room rate remote service
	 */
	public com.sky.skyseries.apm.service.RoomRateService getRoomRateService() {
		return roomRateService;
	}

	/**
	 * Sets the room rate remote service.
	 *
	 * @param roomRateService the room rate remote service
	 */
	public void setRoomRateService(
		com.sky.skyseries.apm.service.RoomRateService roomRateService) {
		this.roomRateService = roomRateService;
	}

	/**
	 * Returns the room status local service.
	 *
	 * @return the room status local service
	 */
	public com.sky.skyseries.apm.service.RoomStatusLocalService getRoomStatusLocalService() {
		return roomStatusLocalService;
	}

	/**
	 * Sets the room status local service.
	 *
	 * @param roomStatusLocalService the room status local service
	 */
	public void setRoomStatusLocalService(
		com.sky.skyseries.apm.service.RoomStatusLocalService roomStatusLocalService) {
		this.roomStatusLocalService = roomStatusLocalService;
	}

	/**
	 * Returns the room status remote service.
	 *
	 * @return the room status remote service
	 */
	public com.sky.skyseries.apm.service.RoomStatusService getRoomStatusService() {
		return roomStatusService;
	}

	/**
	 * Sets the room status remote service.
	 *
	 * @param roomStatusService the room status remote service
	 */
	public void setRoomStatusService(
		com.sky.skyseries.apm.service.RoomStatusService roomStatusService) {
		this.roomStatusService = roomStatusService;
	}

	/**
	 * Returns the room status persistence.
	 *
	 * @return the room status persistence
	 */
	public RoomStatusPersistence getRoomStatusPersistence() {
		return roomStatusPersistence;
	}

	/**
	 * Sets the room status persistence.
	 *
	 * @param roomStatusPersistence the room status persistence
	 */
	public void setRoomStatusPersistence(
		RoomStatusPersistence roomStatusPersistence) {
		this.roomStatusPersistence = roomStatusPersistence;
	}

	/**
	 * Returns the room type local service.
	 *
	 * @return the room type local service
	 */
	public com.sky.skyseries.apm.service.RoomTypeLocalService getRoomTypeLocalService() {
		return roomTypeLocalService;
	}

	/**
	 * Sets the room type local service.
	 *
	 * @param roomTypeLocalService the room type local service
	 */
	public void setRoomTypeLocalService(
		com.sky.skyseries.apm.service.RoomTypeLocalService roomTypeLocalService) {
		this.roomTypeLocalService = roomTypeLocalService;
	}

	/**
	 * Returns the room type remote service.
	 *
	 * @return the room type remote service
	 */
	public com.sky.skyseries.apm.service.RoomTypeService getRoomTypeService() {
		return roomTypeService;
	}

	/**
	 * Sets the room type remote service.
	 *
	 * @param roomTypeService the room type remote service
	 */
	public void setRoomTypeService(
		com.sky.skyseries.apm.service.RoomTypeService roomTypeService) {
		this.roomTypeService = roomTypeService;
	}

	/**
	 * Returns the room type persistence.
	 *
	 * @return the room type persistence
	 */
	public RoomTypePersistence getRoomTypePersistence() {
		return roomTypePersistence;
	}

	/**
	 * Sets the room type persistence.
	 *
	 * @param roomTypePersistence the room type persistence
	 */
	public void setRoomTypePersistence(RoomTypePersistence roomTypePersistence) {
		this.roomTypePersistence = roomTypePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BuildingService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Building.class;
	}

	protected String getModelClassName() {
		return Building.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = buildingPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.sky.skyseries.apm.service.BuildingLocalService.class)
	protected com.sky.skyseries.apm.service.BuildingLocalService buildingLocalService;
	@BeanReference(type = BuildingService.class)
	protected BuildingService buildingService;
	@BeanReference(type = BuildingPersistence.class)
	protected BuildingPersistence buildingPersistence;
	@BeanReference(type = com.sky.skyseries.apm.service.FloorLocalService.class)
	protected com.sky.skyseries.apm.service.FloorLocalService floorLocalService;
	@BeanReference(type = com.sky.skyseries.apm.service.FloorService.class)
	protected com.sky.skyseries.apm.service.FloorService floorService;
	@BeanReference(type = FloorPersistence.class)
	protected FloorPersistence floorPersistence;
	@BeanReference(type = com.sky.skyseries.apm.service.LegalEntityLocalService.class)
	protected com.sky.skyseries.apm.service.LegalEntityLocalService legalEntityLocalService;
	@BeanReference(type = com.sky.skyseries.apm.service.LegalEntityService.class)
	protected com.sky.skyseries.apm.service.LegalEntityService legalEntityService;
	@BeanReference(type = LegalEntityPersistence.class)
	protected LegalEntityPersistence legalEntityPersistence;
	@BeanReference(type = com.sky.skyseries.apm.service.RoomLocalService.class)
	protected com.sky.skyseries.apm.service.RoomLocalService roomLocalService;
	@BeanReference(type = com.sky.skyseries.apm.service.RoomService.class)
	protected com.sky.skyseries.apm.service.RoomService roomService;
	@BeanReference(type = RoomPersistence.class)
	protected RoomPersistence roomPersistence;
	@BeanReference(type = com.sky.skyseries.apm.service.RoomRateLocalService.class)
	protected com.sky.skyseries.apm.service.RoomRateLocalService roomRateLocalService;
	@BeanReference(type = com.sky.skyseries.apm.service.RoomRateService.class)
	protected com.sky.skyseries.apm.service.RoomRateService roomRateService;
	@BeanReference(type = com.sky.skyseries.apm.service.RoomStatusLocalService.class)
	protected com.sky.skyseries.apm.service.RoomStatusLocalService roomStatusLocalService;
	@BeanReference(type = com.sky.skyseries.apm.service.RoomStatusService.class)
	protected com.sky.skyseries.apm.service.RoomStatusService roomStatusService;
	@BeanReference(type = RoomStatusPersistence.class)
	protected RoomStatusPersistence roomStatusPersistence;
	@BeanReference(type = com.sky.skyseries.apm.service.RoomTypeLocalService.class)
	protected com.sky.skyseries.apm.service.RoomTypeLocalService roomTypeLocalService;
	@BeanReference(type = com.sky.skyseries.apm.service.RoomTypeService.class)
	protected com.sky.skyseries.apm.service.RoomTypeService roomTypeService;
	@BeanReference(type = RoomTypePersistence.class)
	protected RoomTypePersistence roomTypePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}