/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sky.skyseries.apm.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.sky.skyseries.apm.model.Building;
import com.sky.skyseries.apm.model.BuildingModel;
import com.sky.skyseries.apm.model.BuildingSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Building service. Represents a row in the &quot;apm_building&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link BuildingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BuildingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BuildingImpl
 * @see Building
 * @see BuildingModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class BuildingModelImpl extends BaseModelImpl<Building>
	implements BuildingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a building model instance should use the {@link Building} interface instead.
	 */
	public static final String TABLE_NAME = "apm_building";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "buildingId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "name2", Types.VARCHAR },
			{ "legalEntityId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("buildingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("legalEntityId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table apm_building (uuid_ VARCHAR(75) null,buildingId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,name2 VARCHAR(75) null,legalEntityId LONG)";
	public static final String TABLE_SQL_DROP = "drop table apm_building";
	public static final String ORDER_BY_JPQL = " ORDER BY building.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY apm_building.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.sky.skyseries.apm.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.sky.skyseries.apm.model.Building"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.sky.skyseries.apm.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.sky.skyseries.apm.model.Building"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.sky.skyseries.apm.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.sky.skyseries.apm.model.Building"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long NAME_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Building toModel(BuildingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Building model = new BuildingImpl();

		model.setUuid(soapModel.getUuid());
		model.setBuildingId(soapModel.getBuildingId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setName2(soapModel.getName2());
		model.setLegalEntityId(soapModel.getLegalEntityId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Building> toModels(BuildingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Building> models = new ArrayList<Building>(soapModels.length);

		for (BuildingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.sky.skyseries.apm.service.util.PropsUtil.get(
				"lock.expiration.time.com.sky.skyseries.apm.model.Building"));

	public BuildingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _buildingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBuildingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _buildingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Building.class;
	}

	@Override
	public String getModelClassName() {
		return Building.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("buildingId", getBuildingId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("name2", getName2());
		attributes.put("legalEntityId", getLegalEntityId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long buildingId = (Long)attributes.get("buildingId");

		if (buildingId != null) {
			setBuildingId(buildingId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String name2 = (String)attributes.get("name2");

		if (name2 != null) {
			setName2(name2);
		}

		Long legalEntityId = (Long)attributes.get("legalEntityId");

		if (legalEntityId != null) {
			setLegalEntityId(legalEntityId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getBuildingId() {
		return _buildingId;
	}

	@Override
	public void setBuildingId(long buildingId) {
		_buildingId = buildingId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getName2() {
		if (_name2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _name2;
		}
	}

	@Override
	public void setName2(String name2) {
		_name2 = name2;
	}

	@JSON
	@Override
	public long getLegalEntityId() {
		return _legalEntityId;
	}

	@Override
	public void setLegalEntityId(long legalEntityId) {
		_legalEntityId = legalEntityId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Building.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Building.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Building toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Building)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BuildingImpl buildingImpl = new BuildingImpl();

		buildingImpl.setUuid(getUuid());
		buildingImpl.setBuildingId(getBuildingId());
		buildingImpl.setGroupId(getGroupId());
		buildingImpl.setCompanyId(getCompanyId());
		buildingImpl.setUserId(getUserId());
		buildingImpl.setUserName(getUserName());
		buildingImpl.setCreateDate(getCreateDate());
		buildingImpl.setModifiedDate(getModifiedDate());
		buildingImpl.setName(getName());
		buildingImpl.setName2(getName2());
		buildingImpl.setLegalEntityId(getLegalEntityId());

		buildingImpl.resetOriginalValues();

		return buildingImpl;
	}

	@Override
	public int compareTo(Building building) {
		int value = 0;

		value = getName().compareTo(building.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Building)) {
			return false;
		}

		Building building = (Building)obj;

		long primaryKey = building.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		BuildingModelImpl buildingModelImpl = this;

		buildingModelImpl._originalUuid = buildingModelImpl._uuid;

		buildingModelImpl._originalGroupId = buildingModelImpl._groupId;

		buildingModelImpl._setOriginalGroupId = false;

		buildingModelImpl._originalCompanyId = buildingModelImpl._companyId;

		buildingModelImpl._setOriginalCompanyId = false;

		buildingModelImpl._setModifiedDate = false;

		buildingModelImpl._originalName = buildingModelImpl._name;

		buildingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Building> toCacheModel() {
		BuildingCacheModel buildingCacheModel = new BuildingCacheModel();

		buildingCacheModel.uuid = getUuid();

		String uuid = buildingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			buildingCacheModel.uuid = null;
		}

		buildingCacheModel.buildingId = getBuildingId();

		buildingCacheModel.groupId = getGroupId();

		buildingCacheModel.companyId = getCompanyId();

		buildingCacheModel.userId = getUserId();

		buildingCacheModel.userName = getUserName();

		String userName = buildingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			buildingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			buildingCacheModel.createDate = createDate.getTime();
		}
		else {
			buildingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			buildingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			buildingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		buildingCacheModel.name = getName();

		String name = buildingCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			buildingCacheModel.name = null;
		}

		buildingCacheModel.name2 = getName2();

		String name2 = buildingCacheModel.name2;

		if ((name2 != null) && (name2.length() == 0)) {
			buildingCacheModel.name2 = null;
		}

		buildingCacheModel.legalEntityId = getLegalEntityId();

		return buildingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", buildingId=");
		sb.append(getBuildingId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", name2=");
		sb.append(getName2());
		sb.append(", legalEntityId=");
		sb.append(getLegalEntityId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.sky.skyseries.apm.model.Building");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>buildingId</column-name><column-value><![CDATA[");
		sb.append(getBuildingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name2</column-name><column-value><![CDATA[");
		sb.append(getName2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>legalEntityId</column-name><column-value><![CDATA[");
		sb.append(getLegalEntityId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Building.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Building.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _buildingId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _name2;
	private long _legalEntityId;
	private long _columnBitmask;
	private Building _escapedModel;
}